export const SET_TERM = 'SET_TERM';
export const SET_SUBJECTFIELDS = 'SET_SUBJECTFIELDS';
export const ADD_SUBJECTFIELD = 'ADD_SUBJECTFIELD';
export const REMOVE_SUBJECTFIELD = 'REMOVE_SUBJECTFIELD';
export const SET_DICTENTRIES = 'SET_DICTENTRIES';
